version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=5000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
